# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='sample',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csample.proto\x12\x06sample\x1a\x1cgoogle/api/annotations.proto\"&\n\x07SaveReq\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x07SaveRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x14\n\x06GetReq\x12\n\n\x02id\x18\x01 \x01(\r\"%\n\x06GetRes\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t2\x86\x01\n\tSampleRPC\x12?\n\x04Save\x12\x0f.sample.SaveReq\x1a\x0f.sample.SaveRes\"\x15\x82\xd3\xe4\x93\x02\x0f\"\n/save/{id}:\x01*\x12\x38\n\x03Get\x12\x0e.sample.GetReq\x1a\x0e.sample.GetRes\"\x11\x82\xd3\xe4\x93\x02\x0b\x12\t/get/{id}b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_SAVEREQ = _descriptor.Descriptor(
  name='SaveReq',
  full_name='sample.SaveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sample.SaveReq.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='sample.SaveReq.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=92,
)


_SAVERES = _descriptor.Descriptor(
  name='SaveRes',
  full_name='sample.SaveRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='sample.SaveRes.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='sample.SaveRes.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='sample.SaveRes.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=149,
)


_GETREQ = _descriptor.Descriptor(
  name='GetReq',
  full_name='sample.GetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sample.GetReq.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=171,
)


_GETRES = _descriptor.Descriptor(
  name='GetRes',
  full_name='sample.GetRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sample.GetRes.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='sample.GetRes.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['SaveReq'] = _SAVEREQ
DESCRIPTOR.message_types_by_name['SaveRes'] = _SAVERES
DESCRIPTOR.message_types_by_name['GetReq'] = _GETREQ
DESCRIPTOR.message_types_by_name['GetRes'] = _GETRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaveReq = _reflection.GeneratedProtocolMessageType('SaveReq', (_message.Message,), {
  'DESCRIPTOR' : _SAVEREQ,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.SaveReq)
  })
_sym_db.RegisterMessage(SaveReq)

SaveRes = _reflection.GeneratedProtocolMessageType('SaveRes', (_message.Message,), {
  'DESCRIPTOR' : _SAVERES,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.SaveRes)
  })
_sym_db.RegisterMessage(SaveRes)

GetReq = _reflection.GeneratedProtocolMessageType('GetReq', (_message.Message,), {
  'DESCRIPTOR' : _GETREQ,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.GetReq)
  })
_sym_db.RegisterMessage(GetReq)

GetRes = _reflection.GeneratedProtocolMessageType('GetRes', (_message.Message,), {
  'DESCRIPTOR' : _GETRES,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.GetRes)
  })
_sym_db.RegisterMessage(GetRes)



_SAMPLERPC = _descriptor.ServiceDescriptor(
  name='SampleRPC',
  full_name='sample.SampleRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=213,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='Save',
    full_name='sample.SampleRPC.Save',
    index=0,
    containing_service=None,
    input_type=_SAVEREQ,
    output_type=_SAVERES,
    serialized_options=b'\202\323\344\223\002\017\"\n/save/{id}:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='sample.SampleRPC.Get',
    index=1,
    containing_service=None,
    input_type=_GETREQ,
    output_type=_GETRES,
    serialized_options=b'\202\323\344\223\002\013\022\t/get/{id}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLERPC)

DESCRIPTOR.services_by_name['SampleRPC'] = _SAMPLERPC

# @@protoc_insertion_point(module_scope)
